version: 2
jobs:
    test:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn --frozen-lockfile
            - save_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - run: npm test
    release:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn --frozen-lockfile
            - run: npx semantic-release@17.4.5
workflows:
    version: 2
    test_and_release:
        # release when tests are successful
        jobs:
            - test
            - release:
                requires:
                    - test
                filters:
                    branches:
                        only:
                            - master
