version: 2.1
orbs:
  cfa: continuousauth/npm@1.0.2
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm test
workflows:
  test_and_release:
    # release when tests are successful
    jobs:
      - test
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
          context: cfa-release
